---
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

trigger:
  - master

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'aws'
      command: 'init'
      backendServiceAWS: 'aws-terraform'
      backendAWSBucketName: 'munakkayalu'
      backendAWSKey: 'terraformdir'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'aws'
      command: 'plan'
      environmentServiceNameAWS: 'aws-terraform'
