---
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

trigger:
  - main

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - bash: terraform init
    displayName: deploy vm
    workingDirectory: '**/ec2-instance' 
  

